config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'status' => 'status#show', defaults: { format: :json }

  get '/auth/:provider/callback' => "sessions#create"
  delete '/logout' => "sessions#destroy"

  resources :events do
    resources :tickets
  end

  resources :retirements, only: %i[new destroy]
end

app/models/async_log.rb
class AsyncLog < ApplicationRecord
end

app/models/author.rb
class Author < SubRecord
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  has_many :book_authors
  has_many :authors, through: :book_authors

  scope :find_price, -> (price) { find_by_price(price) }
  scope :written_about, -> (theme) { where("name link ?", "%#{theme}%") }
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :blog
end

app/models/event.rb
class Event < ApplicationRecord
  # 関連
  belongs_to :owner, optional: true, class_name: 'User', foreign_key: 'owner_id'
  has_many :tickets, dependent: :destroy
  has_one_attached :image, dependent: false

  # アクセサ
  attr_accessor :remove_image

  # フック
  before_save :remove_thumbnail_image, if: -> { remove_image }

  # バリデーション
  validates :name, length: { maximum: 50 },
                    presence: true
                    
  validates :place, length: { maximum: 100 },
                    presence: true

  validates :content, length: { maximum: 2_000 },
                      presence: true

  validates :started_at, presence: true

  validates :ended_at, presence: true

  validates :image, content_type: %i[png jpg jpeg],
                    size: { less_than_or_equal_to: 10.megabytes },
                    dimension: { width: { max: 2_000 }, height: { max: 2_000 } }

  validate :validate_started_at, if: -> { started_at && ended_at }

  # メソッド
  searchkick language: 'japanese' # searchkick用のメソッドが追加されます

  def created_by?(user)
    return false unless user

    owner_id == user.id
  end

  def search_data
    # 戻り値がelasticsearchのインデックスに追加される情報です。
    {
      name: name,
      place: place,
      content:content,
      owner_name: owner&.name,
      started_at: started_at
    }
  end

  # メソッド(Private)
  private

  def validate_started_at
    return if started_at < ended_at

    errors.add(:started_at, 'は終了時間よりも前に設定してください')
  end

  def remove_thumbnail_image
    return unless ActiveRecord::Type::Boolean.new.cast(remove_image)
    self.image = nil
  end
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books
end

app/models/sub_record.rb
class SubRecord < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :sub }
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  # 関連
  belongs_to :user, optional: true
  belongs_to :event

  # バリデーション
  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  # 関連
  has_many :events, foreign_key: 'owner_id', dependent: :nullify
  has_many :tickets, dependent: :nullify
  has_many :participating_events, through: :tickets, source: :event

  # フック
  before_destroy :check_all_events_finished, prepend: true

  # クラスメソッド
  def self.find_or_create_from_auth_hash!(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by!(provider: provider, uid: uid) do |user|
      user.name = nickname
      user.image_url = image_url
    end
  end

  # メソッド(Private)

  private

  def check_all_events_finished
    if self.events.where(ended_at: Time.zone.today.beginning_of_day..).present?
      errors.add(:base, '公開中の未終了イベントが存在します')
    end

    if self.participating_events.where(started_at: ..Time.zone.today.end_of_day, ended_at: Time.zone.now..).present?
      errors.add(:base, '未終了の参加イベントが存在します')
    end

    throw :abort unless errors.empty?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate, only: %i[show]

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to event_path(@event), notice: 'イベントを作成しました'
    else
      respond_to { |format| format.js }
    end
  end

  def show
    @event = Event.find(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event_id: @event.id)
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def edit
    @event = current_user.events.find(params[:id])
  end

  def update
    @event = current_user.events.find(params[:id])

    if @event.update(event_params)
      redirect_to event_path(@event), notice: 'イベントを更新しました'
    else
      respond_to { |format| format.js }
    end
  end

  def destroy
    @event = current_user.events.find(params[:id])

    @event.destroy!
    redirect_to root_path, notice: 'イベントを削除しました'
  end

  private
  
  def event_params
    params.require(:event).permit(:name, :place, :started_at, :ended_at, :content)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, class: "form-horizontal", local: false) do |f| %>
  <div id="errors"></div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :started_at %>
    <div>
      <%= f.datetime_select :started_at, start_year: Time.now.year, end_year: Time.now.year + 1 %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :ended_at %>
    <div>
      <%= f.datetime_select :ended_at, start_year: Time.now.year, end_year: Time.now.year + 1 %>
    </div>
  </div>
  
  <div class="form-group mb-2">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", rows: 10 %>
  </div>

  <div class="form-group mb-2">
    <%= f.label :image %>
    <% if event.image.attached? && event.image.blob&.persisted? %>
      <%= image_tag event.image.variant(resize_to_fit: [200, 200]), class: 'img-thumbnail d-block mb-3' %>
    <% end %>
    <%= f.file_field :image, class: "form-control-file" %>
    <% if event.image.attached? && event.image.blob&.persisted? %>
      <%= f.check_box :remove_image %>
      <%= f.label '画像を削除する ' %>
    <% end %>
  </div>
  
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/events/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("shared/errors", errors: @event.errors) %>"

app/views/events/edit.html.erb
<h1>イベント編集</h1>

<%= render partial: 'form', locals: { event: @event } %>

app/views/events/new.html.erb
<h1>イベント作成</h1>

<%= render partial: 'form', locals: { event: @event } %>

app/views/events/show.html.erb
<h1 class="mt-3 mb-3"><%= @event.name %></h1>

<div class="row">
  <div class="col-8">
    <% if @event.image.attached? %>
      <div class="card mb-2">
        <%= image_tag @event.image, class: "card-img-top" %>
        </div>
    <% end %>

    <div class="card mb-2">
      <h5 class="card-header">イベント内容</h5>
      <div class="card-body">
        <p class="card-text"><%= @event.content %></p>
      </div>
    </div>

    <div class="card mb-2">
      <h5 class="card-header">開催時間</h5>
      <div class="card-body">
        <p class="card-text">
          <%= l(@event.started_at, format: :long) %> - <%= l(@event.ended_at, format: :long) %>
        </p>
      </div>
    </div>

    <div class="card mb-2">
      <h5 class="card-header">開催場所</h5>
      <div class="card-body">
        <p class="card-text"><%= @event.place %></p>
      </div>
    </div>

    <div class="card mb-2">
      <h5 class="card-header">主催者</h5>
      <div class="card-body">
        <% if @event.owner %>
          <%= link_to "https://github.com/#{@event.owner.name}", class: "card-link" do %>
            <%= image_tag @event.owner.image_url, width: 50, height: 50 %> @<%= @event.owner.name %>
          <% end %>
        <% else %>
          <div>退会したユーザーです</div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-4">
    <% if @event.created_by?(current_user) %>
      <%= link_to "イベントを編集する", edit_event_path(@event), class: "btn btn-info btn-lg btn-block mb-1" %>
      <%= link_to "イベントを削除する", event_path(@event), class: "btn btn-danger btn-lg btn-block mb-1", method: :delete, data: { confirm: '本当に削除しますか？' } %>
    <% end %>

    <% if @ticket %>
      <%= link_to "参加をキャンセルする", event_ticket_path(event_id: @event, id: @ticket), class: "btn btn-danger btn-lg btn-block mb-1", method: :delete, data: { confirm: '本当にキャンセルしますか？' } %>
    <% elsif logged_in? %>
      <button class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#createTicket">参加する</button>
      <div class="modal fade" id="createTicket">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="dialogHeader">参加コメント</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            
            <%= form_with(model: @event.tickets.build, url: event_tickets_path(@event), local: false) do |f| %>
              <div class="modal-body">
                <div id="createTicketErrors"></div>
                <%= f.text_field :comment, class: "form-control" %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
                <%= f.button "送信", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <%= link_to "参加する", new_event_ticket_path(@event), class: "btn btn-primary btn-lg btn-block" %>
    <% end %>
    <hr class="card mb-2">
    <h5 class="card-header">参加者</h5>
    <ul class="list-group list-group-flush">
      <% @tickets.each do |ticket| %>
        <li class="list-group-item">
          <% if ticket.user %>
            <%= link_to(url_for_github(ticket.user), class: "card-link") do %>
              <%= image_tag(ticket.user.image_url, width: 20, height: 20, alt: "@#{ticket.user.name}") %>
              @<%= ticket.user.name %>
            <% end %>
            <%= ticket.comment %>
          <% else %>
            <div>退会したユーザーです</div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/events/update.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @event.errors) %>"